/*{
      id: 1,
      nombre: 'Paño de limpieza amarillo',
      precio: 600,
      imagen: '/imagenProd/balerina.webp',
      tipo: 'unidad',
      descripcion:'Ideal para limpiar superficies delicadas sin rayarlas.',
    },
    {
      id: 2,
      nombre: 'Paño de limpieza amarillo x3',
      precio: 1500,
      //precioAnterior: 10000,
      //descuento: '20% OFF',
      imagen: '/imagenProd/balerina.webp',
      tipo: 'oferta',
      descripcion:'Pack de 3 paños para mayor durabilidad y eficiencia.',
    },
    {
      id: 4,
      nombre: 'Encendedor + bombilla para mate',
      precio: 1000,
      imagen: '/imagenProd/combo1.webp',
      tipo: 'combo',
      descripcion:'Bombilla de aluminio para mate y tereré + encendedor recargable.',
      incluye: ['1 bombilla de aluminio', '1 encendedor recargable' ],
    }  
    }*/
const productos = [
  {
    id: 1,
    nombre: "Paño de limpieza amarillo",
    precio: 600,
    imagen: "/imagenProd/balerina.webp",
    tipo: "unidad",
    descripcion: "Ideal para limpiar superficies delicadas sin rayarlas.",
  },
  {
    id: 2,
    nombre: "Paño de limpieza amarillo x3",
    precio: 1500,
    //precioAnterior: 10000,
    //descuento: '20% OFF',
    imagen: "/imagenProd/balerina.webp",
    tipo: "oferta",
    descripcion: "Pack de 3 paños para mayor durabilidad y eficiencia.",
  },
  {
    id: 3,
    nombre: "Pack de 10 unidades de bolsas de residuos 50x70",
    precio: 700,
    //precioAnterior: 10000,
    //descuento: '20% OFF',
    imagen: "/imagenProd/bolsaG.webp",
    tipo: "unidad",
    descripcion: "Bolsas reforzadas resistentes para residuos, tamaño grande.",
  },
  {
    id: 4,
    nombre: "Bombillas para Mate",
    precio: 500,
    imagen: "/imagenProd/bombilla.webp",
    tipo: "unidad",
    descripcion: "Bombillas de aluminio, ideal para mate y tereré.",
  },
  {
    id: 5,
    nombre: "Encendedor + bombilla para mate",
    precio: 1000,
    imagen: "/imagenProd/combo1.webp",
    tipo: "combo",
    descripcion:
      "Bombilla de aluminio para mate y tereré + encendedor recargable.",
    incluye: ["1 bombilla de aluminio", "1 encendedor recargable"],
  },
  {
    id: 6,
    nombre: "Encendedor recargable Candela",
    precio: 550,
    imagen: "/imagenProd/encendedor.webp",
    tipo: "unidad",
    descripcion: "Encendedor recargable, varios colores.",
  },
  {
    id: 7,
    nombre: "Escobillon curvo",
    precio: 2900,
    imagen: "/imagenProd/escobillon.webp",
    tipo: "unidad",
    descripcion: "Escobillón curvo con cerdas resistentes para una limpieza eficaz.",
  },
  {
    id: 8,
    nombre: "Repasador 60x37cm",
    precio: 1350,
    imagen: "/imagenProd/repasador.webp",
    tipo: "unidad",
    descripcion: "Repasador de cocina, variedad de colores.",
  },
  {
    id: 9,
    nombre: "Set de 3 repasadores 60x37cm",
    precio: 3750,
    imagen: "/imagenProd/repasador.webp",
    tipo: "oferta",
    descripcion: "Set de 3 repasadores de cocina, variedad de colores.",
  },
  {
    id: 10,
    nombre: "Set de 5 repasadores 60x37cm",
    precio: 3750,
    imagen: "/imagenProd/repasador.webp",
    tipo: "oferta",
    descripcion: "Set de 5 repasadores de cocina, variedad de colores.",
  },
  {
    id: 11,
    nombre: "Toallon Outlet",
    precio: 6500,
    imagen: "/imagenProd/toallonOutlet.webp",
    tipo: "unidad",
    descripcion: "",
  },
  {
    id: 12,
    nombre: "Tupper térmico 1500ml",
    precio: 1700,
    imagen: "/imagenProd/tupper.webp",
    tipo: "unidad",
    descripcion: "Tupper térmico de 1500ml, apto para frezer y microondas.",
  },
  {
    id: 13,
    nombre: "Set de 3 tuppers térmicos 1500ml",
    precio: 4800,
    imagen: "/imagenProd/tupper.webp",
    tipo: "oferta",
    descripcion: "Set de 3 tuppers térmicos de 1500ml, aptos para frezer y microondas.",
  },
  {
    id: 14,
    nombre: "Set de 5 tuppers térmicos 1500ml",
    precio: 7700,
    imagen: "/imagenProd/tupper.webp",
    tipo: "oferta",
    descripcion: "Set de 5 tuppers térmicos de 1500ml, aptos para frezer y microondas.",
  },
  {
    id: 15,
      nombre: 'Toallon Outlet + 2 repasadores 60x37cm',
      precio: 8900,
      imagen: '/imagenProd/combo2.webp',
      tipo: 'combo',
      descripcion:'Toallon de baño + 2 repasadores de cocina, variedad de colores.',
      incluye: ['1 toallon de baño', '2 repasadores de cocina' ],
  },
  {
    id: 16,
      nombre: '1 paño de limpieza amarillo + 1 pack x10 bolsas de residuos 50x70',
      precio: 1100,
      imagen: '/imagenProd/combo4.webp',
      tipo: 'combo',
      descripcion:'Combo de limpieza para el hogar.',
      incluye: ['1 paño de limpieza amarillo', '1 pack x10 bolsas de residuos 50x70' ],
  },
  {
    id: 17,
      nombre: '4 paños de limpieza amarillo + 2 pack x10 bolsas de residuos 50x70',
      precio: 3300,
      imagen: '/imagenProd/combo3.webp',
      tipo: 'combo',
      descripcion:'Combo de limpieza para el hogar.',
      incluye: ['4 paños de limpieza amarillo', '2 pack x10 bolsas de residuos 50x70' ],
  },
  {
    id: 18,
      nombre: '2 paños de limpieza amarillo + 1 pack x10 bolsas de residuos 50x70 + 1 encendedor recargable',
      precio: 2200,
      imagen: '/imagenProd/combo6.jpeg',
      tipo: 'combo',
      descripcion:'Combo de limpieza para el hogar.',
      incluye: ['2 paños de limpieza amarillo', '1 pack x10 bolsas de residuos 50x70', '1 encendedor recargable' ],
  }
];

export default productos;
